<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.smartbear.testngexamples.ExemplaryTest" tests="4" skipped="1" failures="1" errors="0" timestamp="2021-03-04T11:31:33" hostname="SB-PL-76TMD6M" time="0.054">
	<properties/>
	<testcase name="DEV_T19_testMethod1" classname="com.smartbear.testngexamples.ExemplaryTest" time="0.033"/>
	<testcase name="testMethod3_DEV_T21" classname="com.smartbear.testngexamples.ExemplaryTest" time="0.001">
		<failure message="java.lang.AssertionError: failing test" type="java.lang.AssertionError">java.lang.AssertionError: failing test
			at com.smartbear.testngexamples.ExemplaryTest.testMethod3_DEV_T21(ExemplaryTest.java:26)
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.lang.reflect.Method.invoke(Method.java:498)
			at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
			at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
			at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
			at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
			at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
			at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
			at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
			at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
			at java.util.ArrayList.forEach(ArrayList.java:1259)
			at org.testng.TestRunner.privateRun(TestRunner.java:764)
			at org.testng.TestRunner.run(TestRunner.java:585)
			at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
			at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
			at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
			at org.testng.SuiteRunner.run(SuiteRunner.java:286)
			at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
			at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
			at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
			at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
			at org.testng.TestNG.runSuites(TestNG.java:1069)
			at org.testng.TestNG.run(TestNG.java:1037)
			at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:141)
			at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:90)
			at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.lang.reflect.Method.invoke(Method.java:498)
			at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
			at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
			at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
			at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
			at com.sun.proxy.$Proxy2.stop(Unknown Source)
			at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.lang.reflect.Method.invoke(Method.java:498)
			at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
			at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
			at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
			at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
			at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
			at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
			at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
			at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
			at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
			at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
			at java.lang.Thread.run(Thread.java:748)
		</failure>
	</testcase>
	<testcase name="DEV_T20_testMethod2" classname="com.smartbear.testngexamples.ExemplaryTest" time="0.0"/>
	<testcase name="testMethod4" classname="com.smartbear.testngexamples.ExemplaryTest" time="0.0">
		<skipped/>
	</testcase>
	<system-out><![CDATA[]]></system-out>
	<system-err><![CDATA[]]></system-err>
</testsuite>
